### ISSUE TITLE
Error: Invalid hook call.

### ISSUE THREAD

**Issue by jbcpollak** [BenBrewerBowman/react-lazy-mount#55]
I get the above error trying this component out. Maybe react doesn't support this component anymore?

my code is a pretty basic on:

```
	<LazyMount trigger={show}>
		<MyComponent
                     .....
		/>
	</LazyMount>
```

Here is the text of the error:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
▼ 2 stack frames were expanded.
resolveDispatcher
.../node_modules/react/cjs/react.development.js:1465
useRef
.../node_modules/react/cjs/react.development.js:1504
▲ 2 stack frames were expanded.
useAfterFirstTruthy
src/pickle/dill/src/useAfterFirstTruthy.ts:4
  1 | import { useRef } from 'react';
  2 | 
  3 | export default function useAfterFirstTruthy(val: boolean) {
> 4 |   const mounted: any = useRef();
  5 | 
  6 |   if (val && !mounted.current) {
  7 |     mounted.current = true;
View compiled
LazyMount
.../src/LazyMount.tsx:12
   9 | }
  10 | 
  11 | const LazyMount = ({ children, trigger = false, fallback }: LazyMountProps) => {
> 12 |   const isMounted = useAfterFirstTruthy(trigger);
  13 | 
  14 |   if (!isMounted) {
  15 |     return null;
```

**Comment by BenBrewerBowman** [comment]
@jbcpollak what version of React are you using?

Can you also make sure that you aren't breaking any rules of hooks within the implementation of the component? Error message doesn't look like you are, but thought I'd make sure just in case.

**Comment by jbcpollak** [comment]
I figured this out - I accidentally installed the this package one directory above my actual project, so the way node resolves packages it ended up with two versions of react and that caused the problem. Removing that bad install and reinstalling correctly eliminated the problem.

With that fixed, the package works perfectly and solved my problem - the auto-focus on an `<input autoFocus />` wasn't working unless I loaded it just in time.

Side note: now that React 17 is out, you get a nasty message with npm 7 when installing this package because the peerDependency is for React 16, so you need to use the `--legacy-peer-deps` flag. Any change a new release could be spun with react 17?

**Comment by BenBrewerBowman** [comment]
@jbcpollak awesome glad you figured it out! I will def update this. This was my first pkg I had ever published to npm so I did make some mistakes along the way.

I will change:
```
  "peerDependencies": {
    "react": "^16.10.1"
  },
```

to:
```
  "peerDependencies": {
    "react": ">=16.9.0"
  },
```

I think this will resolve your issue. Might take me a few days to get around to it, but does that sound good?

**Comment by jbcpollak** [comment]
yup, sounds great, thanks!
